defaultSubmissionServerPort: 8000
defaultRetrievalServerPort: 8001
defaultServerPort: 8010
workerExpirationInterval: 30
maxOneTimeCode: 1e8
maxConsecutiveClaimKeyFailures: 8
claimKeyBanDuration: 1

# (Legal requirement: <21). We serve up the last 14. This number 15 includes the current day,
# so 14 days ago is the oldest data.
maxDiagnosisKeyRetentionDays: 15

# A generated keypair can upload up to 28 keys (14 on day 1, plus 14 subsequent days)
initialRemainingKeys: 28

# (Legal requirement: <21)
# When we assign an Application Public Key to a server keypair, we reset the
# created timestamp to the beginning of its existing UTC date. (i.e.
# subtracting anywhere from 00:00 to 23:59 from it)
# From that timestamp, the Application may submit keys for up to 15 days,
# which really means they should submit keys for up to 14 days.
encryptionKeyValidityDays: 15

#OneTimeCodes must be used within 1440 minutes, otherwise they expire.
oneTimeCodeExpiryInMinutes: 1440
assignmentParts: 2
hmacKeyLength: 32