name: S3 backups
on: [pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_BACKUP_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_BACKUP_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
    - name: Get ZIP bundle
      run: |
        wget -O ${{ github.repository }}-`date '+%Y-%m-%d'`.zip https://github.com/cds-snc/${{ github.repository }}/archive/master.zip
    - name: AWS Deploy
      run: |
        aws s3 sync . s3://${{ secrets.AWS_S3_BACKUP_BUCKET }} --exclude='*' --include='${{ github.repository }}/*'
